version: '3'
services:
  nginx:
    build: "./nginx"
    ports:
      - "8080:80"
    networks:
      - app-network
  postgres:
    build: "./postgres"
    networks:
      - app-network
  web:
    build: "./WebApplication"
    networks:
      - app-network

networks: 
  app-network:
   driver: bridge